version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: nba
      POSTGRES_PASSWORD: nba123
      POSTGRES_DB: nba_db
    ports:
      - "5432:5432"
